### PR TITLE
add temp sensor

### PR DESCRIPTION
**Pull request by lucagraziani82**

### CODE REVIEW

**Comment by geoperez** [comment]
Missing LogManager project.

**Comment by geoperez** [comment]
I'll suggest remove the duplicated `WaitMicroseconds `method at GpioPin.cs file

**Comment by geoperez** [comment]
Much better. @mariodivece what do you think?

**Comment by geoperez** [comment]
@lucagraziani82 what version of Visual Studio do you use? I noticed the peripherals project is using the old CSProj format.

**Comment by lucagraziani82** [comment]
Hi Geovanni I use VS2017 but I'have created project with vs2013 pro.

I have to sove this problem?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by geoperez** [comment]
Yes please, to keep the same CSProj format in the solution.

**Comment by lucagraziani82** [comment]
Ok ??

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by geoperez** [comment]
Thank you

**Pull request merged**
